class CreatePuzzles < ActiveRecord::Migration[7.0]
  def change
    create_table :puzzles do |t|
      t.integer :r0c0 ,limit:1
      t.integer :r0c1 ,limit:1
      t.integer :r0c2 ,limit:1
      t.integer :r0c3 ,limit:1
      t.integer :r0c4 ,limit:1
      t.integer :r0c5 ,limit:1
      t.integer :r0c6 ,limit:1
      t.integer :r0c7 ,limit:1
      t.integer :r0c8 ,limit:1
      t.integer :r1c0 ,limit:1
      t.integer :r1c1 ,limit:1
      t.integer :r1c2 ,limit:1
      t.integer :r1c3 ,limit:1
      t.integer :r1c4 ,limit:1
      t.integer :r1c5 ,limit:1
      t.integer :r1c6 ,limit:1
      t.integer :r1c7 ,limit:1
      t.integer :r1c8 ,limit:1
      t.integer :r2c0 ,limit:1
      t.integer :r2c1 ,limit:1
      t.integer :r2c2 ,limit:1
      t.integer :r2c3 ,limit:1
      t.integer :r2c4 ,limit:1
      t.integer :r2c5 ,limit:1
      t.integer :r2c6 ,limit:1
      t.integer :r2c7 ,limit:1
      t.integer :r2c8 ,limit:1
      t.integer :r3c0 ,limit:1
      t.integer :r3c1 ,limit:1
      t.integer :r3c2 ,limit:1
      t.integer :r3c3 ,limit:1
      t.integer :r3c4 ,limit:1
      t.integer :r3c5 ,limit:1
      t.integer :r3c6 ,limit:1
      t.integer :r3c7 ,limit:1
      t.integer :r3c8 ,limit:1
      t.integer :r4c0 ,limit:1
      t.integer :r4c1 ,limit:1
      t.integer :r4c2 ,limit:1
      t.integer :r4c3 ,limit:1
      t.integer :r4c4 ,limit:1
      t.integer :r4c5 ,limit:1
      t.integer :r4c6 ,limit:1
      t.integer :r4c7 ,limit:1
      t.integer :r4c8 ,limit:1
      t.integer :r5c0 ,limit:1
      t.integer :r5c1 ,limit:1
      t.integer :r5c2 ,limit:1
      t.integer :r5c3 ,limit:1
      t.integer :r5c4 ,limit:1
      t.integer :r5c5 ,limit:1
      t.integer :r5c6 ,limit:1
      t.integer :r5c7 ,limit:1
      t.integer :r5c8 ,limit:1
      t.integer :r6c0 ,limit:1
      t.integer :r6c1 ,limit:1
      t.integer :r6c2 ,limit:1
      t.integer :r6c3 ,limit:1
      t.integer :r6c4 ,limit:1
      t.integer :r6c5 ,limit:1
      t.integer :r6c6 ,limit:1
      t.integer :r6c7 ,limit:1
      t.integer :r6c8 ,limit:1
      t.integer :r7c0 ,limit:1
      t.integer :r7c1 ,limit:1
      t.integer :r7c2 ,limit:1
      t.integer :r7c3 ,limit:1
      t.integer :r7c4 ,limit:1
      t.integer :r7c5 ,limit:1
      t.integer :r7c6 ,limit:1
      t.integer :r7c7 ,limit:1
      t.integer :r7c8 ,limit:1
      t.integer :r8c0 ,limit:1
      t.integer :r8c1 ,limit:1
      t.integer :r8c2 ,limit:1
      t.integer :r8c3 ,limit:1
      t.integer :r8c4 ,limit:1
      t.integer :r8c5 ,limit:1
      t.integer :r8c6 ,limit:1
      t.integer :r8c7 ,limit:1
      t.integer :r8c8 ,limit:1

      t.timestamps
    end
  end
end
